/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.rcsbusinessmessaging.v1.model;

/**
 * A message sent from the agent to a user.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AgentMessage extends com.google.api.client.json.GenericJson {

  /**
   * The content of the agent message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AgentContentMessage contentMessage;

  /**
   * Optional. Timestamp in UTC of when this resource is considered expired. This value is provided
   * on output if it is set or if the TTL field is set.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String expireTime;

  /**
   * The message traffic type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String messageTrafficType;

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves "phones/{E.164}/agentMessages/{messageId}", where {E.164} is the user's phone
   * number in E.164 format and {messageId} is the agent-assigned ID of the agent message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Output only. Classifies the message as RICH or RICH_MEDIA. Only populated for US phone numbers
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RichMessageClassification richMessageClassification;

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves the time when the message is sent to the user.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String sendTime;

  /**
   * Optional. Input only. How long the message will live before it is automatically revoked.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String ttl;

  /**
   * The content of the agent message.
   * @return value or {@code null} for none
   */
  public AgentContentMessage getContentMessage() {
    return contentMessage;
  }

  /**
   * The content of the agent message.
   * @param contentMessage contentMessage or {@code null} for none
   */
  public AgentMessage setContentMessage(AgentContentMessage contentMessage) {
    this.contentMessage = contentMessage;
    return this;
  }

  /**
   * Optional. Timestamp in UTC of when this resource is considered expired. This value is provided
   * on output if it is set or if the TTL field is set.
   * @return value or {@code null} for none
   */
  public String getExpireTime() {
    return expireTime;
  }

  /**
   * Optional. Timestamp in UTC of when this resource is considered expired. This value is provided
   * on output if it is set or if the TTL field is set.
   * @param expireTime expireTime or {@code null} for none
   */
  public AgentMessage setExpireTime(String expireTime) {
    this.expireTime = expireTime;
    return this;
  }

  /**
   * The message traffic type.
   * @return value or {@code null} for none
   */
  public java.lang.String getMessageTrafficType() {
    return messageTrafficType;
  }

  /**
   * The message traffic type.
   * @param messageTrafficType messageTrafficType or {@code null} for none
   */
  public AgentMessage setMessageTrafficType(java.lang.String messageTrafficType) {
    this.messageTrafficType = messageTrafficType;
    return this;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves "phones/{E.164}/agentMessages/{messageId}", where {E.164} is the user's phone
   * number in E.164 format and {messageId} is the agent-assigned ID of the agent message.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves "phones/{E.164}/agentMessages/{messageId}", where {E.164} is the user's phone
   * number in E.164 format and {messageId} is the agent-assigned ID of the agent message.
   * @param name name or {@code null} for none
   */
  public AgentMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Output only. Classifies the message as RICH or RICH_MEDIA. Only populated for US phone numbers
   * @return value or {@code null} for none
   */
  public RichMessageClassification getRichMessageClassification() {
    return richMessageClassification;
  }

  /**
   * Output only. Classifies the message as RICH or RICH_MEDIA. Only populated for US phone numbers
   * @param richMessageClassification richMessageClassification or {@code null} for none
   */
  public AgentMessage setRichMessageClassification(RichMessageClassification richMessageClassification) {
    this.richMessageClassification = richMessageClassification;
    return this;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves the time when the message is sent to the user.
   * @return value or {@code null} for none
   */
  public String getSendTime() {
    return sendTime;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating an agent message. The
   * field resolves the time when the message is sent to the user.
   * @param sendTime sendTime or {@code null} for none
   */
  public AgentMessage setSendTime(String sendTime) {
    this.sendTime = sendTime;
    return this;
  }

  /**
   * Optional. Input only. How long the message will live before it is automatically revoked.
   * @return value or {@code null} for none
   */
  public String getTtl() {
    return ttl;
  }

  /**
   * Optional. Input only. How long the message will live before it is automatically revoked.
   * @param ttl ttl or {@code null} for none
   */
  public AgentMessage setTtl(String ttl) {
    this.ttl = ttl;
    return this;
  }

  @Override
  public AgentMessage set(String fieldName, Object value) {
    return (AgentMessage) super.set(fieldName, value);
  }

  @Override
  public AgentMessage clone() {
    return (AgentMessage) super.clone();
  }

}
