/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.rcsbusinessmessaging.v1.model;

/**
 * Initiate the recording and sending of an audio or video message.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ComposeRecordingMessage extends com.google.api.client.json.GenericJson {

  /**
   * Prefilled destination phone number by chatbot.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phoneNumber;

  /**
   * The type of the recording action.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * Prefilled destination phone number by chatbot.
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Prefilled destination phone number by chatbot.
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  public ComposeRecordingMessage setPhoneNumber(java.lang.String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * The type of the recording action.
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * The type of the recording action.
   * @param type type or {@code null} for none
   */
  public ComposeRecordingMessage setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public ComposeRecordingMessage set(String fieldName, Object value) {
    return (ComposeRecordingMessage) super.set(fieldName, value);
  }

  @Override
  public ComposeRecordingMessage clone() {
    return (ComposeRecordingMessage) super.clone();
  }

}
