/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.rcsbusinessmessaging.v1.model;

/**
 * Model definition for RichMessageClassification.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RichMessageClassification extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String classificationType;

  /**
   * Number of 160 character segments in the text, rounded up. For example, if there are 300
   * characters in the message, this value will be 2. Only populated for RICH_MESSAGE
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer segmentCount;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClassificationType() {
    return classificationType;
  }

  /**
   * @param classificationType classificationType or {@code null} for none
   */
  public RichMessageClassification setClassificationType(java.lang.String classificationType) {
    this.classificationType = classificationType;
    return this;
  }

  /**
   * Number of 160 character segments in the text, rounded up. For example, if there are 300
   * characters in the message, this value will be 2. Only populated for RICH_MESSAGE
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSegmentCount() {
    return segmentCount;
  }

  /**
   * Number of 160 character segments in the text, rounded up. For example, if there are 300
   * characters in the message, this value will be 2. Only populated for RICH_MESSAGE
   * @param segmentCount segmentCount or {@code null} for none
   */
  public RichMessageClassification setSegmentCount(java.lang.Integer segmentCount) {
    this.segmentCount = segmentCount;
    return this;
  }

  @Override
  public RichMessageClassification set(String fieldName, Object value) {
    return (RichMessageClassification) super.set(fieldName, value);
  }

  @Override
  public RichMessageClassification clone() {
    return (RichMessageClassification) super.clone();
  }

}
