/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A conversational entity that represents a brand.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Agent extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The name of the brand associated with the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String brandName;

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * The unique identifier of the agent. Read-only. Defined by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Detailed agent information for RCS for Business.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RcsBusinessMessagingAgent rcsBusinessMessagingAgent;

  /**
   * Output only. The name of the brand associated with the agent.
   * @return value or {@code null} for none
   */
  public java.lang.String getBrandName() {
    return brandName;
  }

  /**
   * Output only. The name of the brand associated with the agent.
   * @param brandName brandName or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Agent setBrandName(java.lang.String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * @param displayName displayName or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Agent setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The unique identifier of the agent. Read-only. Defined by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The unique identifier of the agent. Read-only. Defined by the platform.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Agent setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Detailed agent information for RCS for Business.
   * @return value or {@code null} for none
   */
  public RcsBusinessMessagingAgent getRcsBusinessMessagingAgent() {
    return rcsBusinessMessagingAgent;
  }

  /**
   * Detailed agent information for RCS for Business.
   * @param rcsBusinessMessagingAgent rcsBusinessMessagingAgent or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Agent setRcsBusinessMessagingAgent(RcsBusinessMessagingAgent rcsBusinessMessagingAgent) {
    this.rcsBusinessMessagingAgent = rcsBusinessMessagingAgent;
    return this;
  }

  @Override
  public Agent set(String fieldName, Object value) {
    return (Agent) super.set(fieldName, value);
  }

  @Override
  public Agent clone() {
    return (Agent) super.clone();
  }

}
