/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Information about webhook for a Business Messages agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AgentWebhookIntegration extends com.google.api.client.json.GenericJson {

  /**
   * Input only. The verification token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String verificationToken;

  /**
   * Required. The webhook URL where the messages are delivered.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String webhookUri;

  /**
   * Input only. The verification token.
   * @return value or {@code null} for none
   */
  public java.lang.String getVerificationToken() {
    return verificationToken;
  }

  /**
   * Input only. The verification token.
   * @param verificationToken verificationToken or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentWebhookIntegration setVerificationToken(java.lang.String verificationToken) {
    this.verificationToken = verificationToken;
    return this;
  }

  /**
   * Required. The webhook URL where the messages are delivered.
   * @return value or {@code null} for none
   */
  public java.lang.String getWebhookUri() {
    return webhookUri;
  }

  /**
   * Required. The webhook URL where the messages are delivered.
   * @param webhookUri webhookUri or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentWebhookIntegration setWebhookUri(java.lang.String webhookUri) {
    this.webhookUri = webhookUri;
    return this;
  }

  @Override
  public AgentWebhookIntegration set(String fieldName, Object value) {
    return (AgentWebhookIntegration) super.set(fieldName, value);
  }

  @Override
  public AgentWebhookIntegration clone() {
    return (AgentWebhookIntegration) super.clone();
  }

}
