/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Performance metrics for an agent in a country. *Note*: This API is expected to evolve. Your
 * client should be resilient to the addition of new fields in the future.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AgentPerformance extends com.google.api.client.json.GenericJson {

  /**
   * The agent's use case
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentUseCase;

  /**
   * The country dimension for the given performance metrics. Given as an [ISO 3166 Alpha-2 country
   * code](https://www.iso.org/obp/ui/#search/code/). For example, "US" for the United States of
   * America.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String countryCode;

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * The timestamp representing the end of the period for which metrics were calculated. Metrics,
   * including reputation, are calculated based on data up to this timestamp. This timestamp is the
   * most recent midnight Pacific Time (PT). *Note*: Due to daily processing after midnight PT,
   * metrics might not be updated until several hours after midnight PT.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String metricsPeriodEndTime;

  /**
   * The unique identifier of the agent. Defined by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Reputation of the agent in the given country.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String reputation;

  /**
   * Traffic limit for the agent (messages per user per month) in the given country. If the agent is
   * not subject to traffic limits, the value will not be set.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer trafficLimit;

  /**
   * The agent's use case
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentUseCase() {
    return agentUseCase;
  }

  /**
   * The agent's use case
   * @param agentUseCase agentUseCase or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setAgentUseCase(java.lang.String agentUseCase) {
    this.agentUseCase = agentUseCase;
    return this;
  }

  /**
   * The country dimension for the given performance metrics. Given as an [ISO 3166 Alpha-2 country
   * code](https://www.iso.org/obp/ui/#search/code/). For example, "US" for the United States of
   * America.
   * @return value or {@code null} for none
   */
  public java.lang.String getCountryCode() {
    return countryCode;
  }

  /**
   * The country dimension for the given performance metrics. Given as an [ISO 3166 Alpha-2 country
   * code](https://www.iso.org/obp/ui/#search/code/). For example, "US" for the United States of
   * America.
   * @param countryCode countryCode or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setCountryCode(java.lang.String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 100 characters. Not modifiable
   * after agent verification.
   * @param displayName displayName or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The timestamp representing the end of the period for which metrics were calculated. Metrics,
   * including reputation, are calculated based on data up to this timestamp. This timestamp is the
   * most recent midnight Pacific Time (PT). *Note*: Due to daily processing after midnight PT,
   * metrics might not be updated until several hours after midnight PT.
   * @return value or {@code null} for none
   */
  public String getMetricsPeriodEndTime() {
    return metricsPeriodEndTime;
  }

  /**
   * The timestamp representing the end of the period for which metrics were calculated. Metrics,
   * including reputation, are calculated based on data up to this timestamp. This timestamp is the
   * most recent midnight Pacific Time (PT). *Note*: Due to daily processing after midnight PT,
   * metrics might not be updated until several hours after midnight PT.
   * @param metricsPeriodEndTime metricsPeriodEndTime or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setMetricsPeriodEndTime(String metricsPeriodEndTime) {
    this.metricsPeriodEndTime = metricsPeriodEndTime;
    return this;
  }

  /**
   * The unique identifier of the agent. Defined by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The unique identifier of the agent. Defined by the platform.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Reputation of the agent in the given country.
   * @return value or {@code null} for none
   */
  public java.lang.String getReputation() {
    return reputation;
  }

  /**
   * Reputation of the agent in the given country.
   * @param reputation reputation or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setReputation(java.lang.String reputation) {
    this.reputation = reputation;
    return this;
  }

  /**
   * Traffic limit for the agent (messages per user per month) in the given country. If the agent is
   * not subject to traffic limits, the value will not be set.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTrafficLimit() {
    return trafficLimit;
  }

  /**
   * Traffic limit for the agent (messages per user per month) in the given country. If the agent is
   * not subject to traffic limits, the value will not be set.
   * @param trafficLimit trafficLimit or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentPerformance setTrafficLimit(java.lang.Integer trafficLimit) {
    this.trafficLimit = trafficLimit;
    return this;
  }

  @Override
  public AgentPerformance set(String fieldName, Object value) {
    return (AgentPerformance) super.set(fieldName, value);
  }

  @Override
  public AgentPerformance clone() {
    return (AgentPerformance) super.clone();
  }

}
