/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Details about an agent launch.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AgentLaunch extends com.google.api.client.json.GenericJson {

  /**
   * Required. The identifier for launch.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Launch details for an RCS for Business agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RcsBusinessMessagingLaunch rcsBusinessMessaging;

  /**
   * Required. The identifier for launch.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Required. The identifier for launch.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentLaunch setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Launch details for an RCS for Business agent.
   * @return value or {@code null} for none
   */
  public RcsBusinessMessagingLaunch getRcsBusinessMessaging() {
    return rcsBusinessMessaging;
  }

  /**
   * Launch details for an RCS for Business agent.
   * @param rcsBusinessMessaging rcsBusinessMessaging or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public AgentLaunch setRcsBusinessMessaging(RcsBusinessMessagingLaunch rcsBusinessMessaging) {
    this.rcsBusinessMessaging = rcsBusinessMessaging;
    return this;
  }

  @Override
  public AgentLaunch set(String fieldName, Object value) {
    return (AgentLaunch) super.set(fieldName, value);
  }

  @Override
  public AgentLaunch clone() {
    return (AgentLaunch) super.clone();
  }

}
