/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Contact details
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCommunicationsBusinesscommunicationsV1PartnerContact extends com.google.api.client.json.GenericJson {

  /**
   * Email of the contact person.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * Name of the contact person.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Phone number of the contact person.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Phone phoneNumber;

  /**
   * Email of the contact person.
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * Email of the contact person.
   * @param email email or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public GoogleCommunicationsBusinesscommunicationsV1PartnerContact setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * Name of the contact person.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Name of the contact person.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public GoogleCommunicationsBusinesscommunicationsV1PartnerContact setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Phone number of the contact person.
   * @return value or {@code null} for none
   */
  public Phone getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Phone number of the contact person.
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public GoogleCommunicationsBusinesscommunicationsV1PartnerContact setPhoneNumber(Phone phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  @Override
  public GoogleCommunicationsBusinesscommunicationsV1PartnerContact set(String fieldName, Object value) {
    return (GoogleCommunicationsBusinesscommunicationsV1PartnerContact) super.set(fieldName, value);
  }

  @Override
  public GoogleCommunicationsBusinesscommunicationsV1PartnerContact clone() {
    return (GoogleCommunicationsBusinesscommunicationsV1PartnerContact) super.clone();
  }

}
