/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Information about the integration.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Integration extends com.google.api.client.json.GenericJson {

  /**
   * Information about webhook for an agent. If a webhook is configured at an agent level, it will
   * override the webhook at the partner level.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AgentWebhookIntegration agentWebhookIntegration;

  /**
   * Information about an associated Dialogflow CX project.
   * https://cloud.google.com/dialogflow/cx/docs/basics
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DialogflowCxIntegration dialogflowCxIntegration;

  /**
   * Information about an associated Dialogflow ES project.
   * https://cloud.google.com/dialogflow/es/docs
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DialogflowEsIntegration dialogflowEsIntegration;

  /**
   * Output only. The unique identifier of the integration. Read-only. Defined by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Output only. Integration status.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * Information about webhook for an agent. If a webhook is configured at an agent level, it will
   * override the webhook at the partner level.
   * @return value or {@code null} for none
   */
  public AgentWebhookIntegration getAgentWebhookIntegration() {
    return agentWebhookIntegration;
  }

  /**
   * Information about webhook for an agent. If a webhook is configured at an agent level, it will
   * override the webhook at the partner level.
   * @param agentWebhookIntegration agentWebhookIntegration or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Integration setAgentWebhookIntegration(AgentWebhookIntegration agentWebhookIntegration) {
    this.agentWebhookIntegration = agentWebhookIntegration;
    return this;
  }

  /**
   * Information about an associated Dialogflow CX project.
   * https://cloud.google.com/dialogflow/cx/docs/basics
   * @return value or {@code null} for none
   */
  public DialogflowCxIntegration getDialogflowCxIntegration() {
    return dialogflowCxIntegration;
  }

  /**
   * Information about an associated Dialogflow CX project.
   * https://cloud.google.com/dialogflow/cx/docs/basics
   * @param dialogflowCxIntegration dialogflowCxIntegration or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Integration setDialogflowCxIntegration(DialogflowCxIntegration dialogflowCxIntegration) {
    this.dialogflowCxIntegration = dialogflowCxIntegration;
    return this;
  }

  /**
   * Information about an associated Dialogflow ES project.
   * https://cloud.google.com/dialogflow/es/docs
   * @return value or {@code null} for none
   */
  public DialogflowEsIntegration getDialogflowEsIntegration() {
    return dialogflowEsIntegration;
  }

  /**
   * Information about an associated Dialogflow ES project.
   * https://cloud.google.com/dialogflow/es/docs
   * @param dialogflowEsIntegration dialogflowEsIntegration or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Integration setDialogflowEsIntegration(DialogflowEsIntegration dialogflowEsIntegration) {
    this.dialogflowEsIntegration = dialogflowEsIntegration;
    return this;
  }

  /**
   * Output only. The unique identifier of the integration. Read-only. Defined by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Output only. The unique identifier of the integration. Read-only. Defined by the platform.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Integration setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Output only. Integration status.
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Output only. Integration status.
   * @param status status or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Integration setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  @Override
  public Integration set(String fieldName, Object value) {
    return (Integration) super.set(fieldName, value);
  }

  @Override
  public Integration clone() {
    return (Integration) super.clone();
  }

}
