/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Returns a list of agent performances.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ListAgentPerformancesResponse extends com.google.api.client.json.GenericJson {

  /**
   * List of agent performances.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<AgentPerformance> agentPerformances;

  /**
   * Optional. The pagination token to retrieve the next page of results. If the value is "", it
   * means no further results for the request.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nextPageToken;

  /**
   * List of agent performances.
   * @return value or {@code null} for none
   */
  public java.util.List<AgentPerformance> getAgentPerformances() {
    return agentPerformances;
  }

  /**
   * List of agent performances.
   * @param agentPerformances agentPerformances or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public ListAgentPerformancesResponse setAgentPerformances(java.util.List<AgentPerformance> agentPerformances) {
    this.agentPerformances = agentPerformances;
    return this;
  }

  /**
   * Optional. The pagination token to retrieve the next page of results. If the value is "", it
   * means no further results for the request.
   * @return value or {@code null} for none
   */
  public java.lang.String getNextPageToken() {
    return nextPageToken;
  }

  /**
   * Optional. The pagination token to retrieve the next page of results. If the value is "", it
   * means no further results for the request.
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public ListAgentPerformancesResponse setNextPageToken(java.lang.String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public ListAgentPerformancesResponse set(String fieldName, Object value) {
    return (ListAgentPerformancesResponse) super.set(fieldName, value);
  }

  @Override
  public ListAgentPerformancesResponse clone() {
    return (ListAgentPerformancesResponse) super.clone();
  }

}
