/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * The Dialogflow operation information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class OperationInfo extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Error result, if any.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Status error;

  /**
   * Output only. The server-assigned name (operation Id), which is only unique within the same
   * service that originally returns it.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operationName;

  /**
   * Output only. Dialogflow Operation state.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operationState;

  /**
   * Output only. Dialogflow Operation type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operationType;

  /**
   * Output only. Error result, if any.
   * @return value or {@code null} for none
   */
  public Status getError() {
    return error;
  }

  /**
   * Output only. Error result, if any.
   * @param error error or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public OperationInfo setError(Status error) {
    this.error = error;
    return this;
  }

  /**
   * Output only. The server-assigned name (operation Id), which is only unique within the same
   * service that originally returns it.
   * @return value or {@code null} for none
   */
  public java.lang.String getOperationName() {
    return operationName;
  }

  /**
   * Output only. The server-assigned name (operation Id), which is only unique within the same
   * service that originally returns it.
   * @param operationName operationName or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public OperationInfo setOperationName(java.lang.String operationName) {
    this.operationName = operationName;
    return this;
  }

  /**
   * Output only. Dialogflow Operation state.
   * @return value or {@code null} for none
   */
  public java.lang.String getOperationState() {
    return operationState;
  }

  /**
   * Output only. Dialogflow Operation state.
   * @param operationState operationState or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public OperationInfo setOperationState(java.lang.String operationState) {
    this.operationState = operationState;
    return this;
  }

  /**
   * Output only. Dialogflow Operation type.
   * @return value or {@code null} for none
   */
  public java.lang.String getOperationType() {
    return operationType;
  }

  /**
   * Output only. Dialogflow Operation type.
   * @param operationType operationType or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public OperationInfo setOperationType(java.lang.String operationType) {
    this.operationType = operationType;
    return this;
  }

  @Override
  public OperationInfo set(String fieldName, Object value) {
    return (OperationInfo) super.set(fieldName, value);
  }

  @Override
  public OperationInfo clone() {
    return (OperationInfo) super.clone();
  }

}
