/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Partner associated with the agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PartnerEntry extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The public name of the company for the given partner. E.g. Twilio, HeyMarket etc.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String company;

  /**
   * Output only. The name that will be displayed to businesses to associate partners for products.
   * Should be unique among partners.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * Output only. Unique identifier for partner.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String partnerId;

  /**
   * Output only. The public name of the company for the given partner. E.g. Twilio, HeyMarket etc.
   * @return value or {@code null} for none
   */
  public java.lang.String getCompany() {
    return company;
  }

  /**
   * Output only. The public name of the company for the given partner. E.g. Twilio, HeyMarket etc.
   * @param company company or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public PartnerEntry setCompany(java.lang.String company) {
    this.company = company;
    return this;
  }

  /**
   * Output only. The name that will be displayed to businesses to associate partners for products.
   * Should be unique among partners.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Output only. The name that will be displayed to businesses to associate partners for products.
   * Should be unique among partners.
   * @param displayName displayName or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public PartnerEntry setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Output only. Unique identifier for partner.
   * @return value or {@code null} for none
   */
  public java.lang.String getPartnerId() {
    return partnerId;
  }

  /**
   * Output only. Unique identifier for partner.
   * @param partnerId partnerId or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public PartnerEntry setPartnerId(java.lang.String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

  @Override
  public PartnerEntry set(String fieldName, Object value) {
    return (PartnerEntry) super.set(fieldName, value);
  }

  @Override
  public PartnerEntry clone() {
    return (PartnerEntry) super.clone();
  }

}
