/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A phone number associated with the agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PhoneEntry extends com.google.api.client.json.GenericJson {

  /**
   * Required. Label for the phone number.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * Required. Phone number in two possible formats: either the full E.164 format (for example,
   * "+12223334444") or an unformatted local/toll-free phone number without '+', prefix, or country
   * code (for example, "6502530000"). Note: emergency numbers are not allowed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Phone phoneNumber;

  /**
   * Required. Label for the phone number.
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * Required. Label for the phone number.
   * @param label label or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public PhoneEntry setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  /**
   * Required. Phone number in two possible formats: either the full E.164 format (for example,
   * "+12223334444") or an unformatted local/toll-free phone number without '+', prefix, or country
   * code (for example, "6502530000"). Note: emergency numbers are not allowed.
   * @return value or {@code null} for none
   */
  public Phone getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Required. Phone number in two possible formats: either the full E.164 format (for example,
   * "+12223334444") or an unformatted local/toll-free phone number without '+', prefix, or country
   * code (for example, "6502530000"). Note: emergency numbers are not allowed.
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public PhoneEntry setPhoneNumber(Phone phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  @Override
  public PhoneEntry set(String fieldName, Object value) {
    return (PhoneEntry) super.set(fieldName, value);
  }

  @Override
  public PhoneEntry clone() {
    return (PhoneEntry) super.clone();
  }

}
