/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * If Google manages the launch region, questionnaire details are available to Google for the
 * purpose of reviewing the agent's launch.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Questionnaire extends com.google.api.client.json.GenericJson {

  /**
   * Required. Agent access instructions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentAccessInstructions;

  /**
   * Required. Point of contacts.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Contact> contacts;

  /**
   * Required. Description of interactions the agent will have with users.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String interactionsDescription;

  /**
   * Optional. Description of how you obtain opt-in to message users with the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String optinDescription;

  /**
   * Required. Description of the message the agent sends when a user opts out.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String optoutDescription;

  /**
   * Optional. Publicly available URIs for screenshots of the agent. For review purposes only.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> screenshotUris;

  /**
   * Required. Description of actions that trigger messages to users.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String triggerDescription;

  /**
   * Optional. Publicly available URIs for videos of the agent. For review purposes only.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> videoUris;

  /**
   * Required. Agent access instructions.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentAccessInstructions() {
    return agentAccessInstructions;
  }

  /**
   * Required. Agent access instructions.
   * @param agentAccessInstructions agentAccessInstructions or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setAgentAccessInstructions(java.lang.String agentAccessInstructions) {
    this.agentAccessInstructions = agentAccessInstructions;
    return this;
  }

  /**
   * Required. Point of contacts.
   * @return value or {@code null} for none
   */
  public java.util.List<Contact> getContacts() {
    return contacts;
  }

  /**
   * Required. Point of contacts.
   * @param contacts contacts or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setContacts(java.util.List<Contact> contacts) {
    this.contacts = contacts;
    return this;
  }

  /**
   * Required. Description of interactions the agent will have with users.
   * @return value or {@code null} for none
   */
  public java.lang.String getInteractionsDescription() {
    return interactionsDescription;
  }

  /**
   * Required. Description of interactions the agent will have with users.
   * @param interactionsDescription interactionsDescription or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setInteractionsDescription(java.lang.String interactionsDescription) {
    this.interactionsDescription = interactionsDescription;
    return this;
  }

  /**
   * Optional. Description of how you obtain opt-in to message users with the agent.
   * @return value or {@code null} for none
   */
  public java.lang.String getOptinDescription() {
    return optinDescription;
  }

  /**
   * Optional. Description of how you obtain opt-in to message users with the agent.
   * @param optinDescription optinDescription or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setOptinDescription(java.lang.String optinDescription) {
    this.optinDescription = optinDescription;
    return this;
  }

  /**
   * Required. Description of the message the agent sends when a user opts out.
   * @return value or {@code null} for none
   */
  public java.lang.String getOptoutDescription() {
    return optoutDescription;
  }

  /**
   * Required. Description of the message the agent sends when a user opts out.
   * @param optoutDescription optoutDescription or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setOptoutDescription(java.lang.String optoutDescription) {
    this.optoutDescription = optoutDescription;
    return this;
  }

  /**
   * Optional. Publicly available URIs for screenshots of the agent. For review purposes only.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getScreenshotUris() {
    return screenshotUris;
  }

  /**
   * Optional. Publicly available URIs for screenshots of the agent. For review purposes only.
   * @param screenshotUris screenshotUris or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setScreenshotUris(java.util.List<java.lang.String> screenshotUris) {
    this.screenshotUris = screenshotUris;
    return this;
  }

  /**
   * Required. Description of actions that trigger messages to users.
   * @return value or {@code null} for none
   */
  public java.lang.String getTriggerDescription() {
    return triggerDescription;
  }

  /**
   * Required. Description of actions that trigger messages to users.
   * @param triggerDescription triggerDescription or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setTriggerDescription(java.lang.String triggerDescription) {
    this.triggerDescription = triggerDescription;
    return this;
  }

  /**
   * Optional. Publicly available URIs for videos of the agent. For review purposes only.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getVideoUris() {
    return videoUris;
  }

  /**
   * Optional. Publicly available URIs for videos of the agent. For review purposes only.
   * @param videoUris videoUris or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Questionnaire setVideoUris(java.util.List<java.lang.String> videoUris) {
    this.videoUris = videoUris;
    return this;
  }

  @Override
  public Questionnaire set(String fieldName, Object value) {
    return (Questionnaire) super.set(fieldName, value);
  }

  @Override
  public Questionnaire clone() {
    return (Questionnaire) super.clone();
  }

}
