/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Agent information specifically related to RCS for Business. For agent creation, it's recommended
 * to provide at least one contact method (phone, email, or website) with a corresponding label. For
 * agent launch, at least one phone or email contact with a corresponding label is required.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RcsBusinessMessagingAgent extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Use case of bot.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentUseCase;

  /**
   * Required. Billing configuration for the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RcsBusinessMessagingAgentBillingConfig billingConfig;

  /**
   * Required. Theme color of the agent that is visible to users in hex format. For example,
   * #FF6347.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String color;

  /**
   * Required. Description of the agent that is visible to users. Maximum 100 characters. See [Edit
   * agent information](https://developers.google.com/business-communications/rcs-business-
   * messaging/guides/build/agents/edit-agent-information?hl=en#edit_your_agents_information) for
   * detailed requirements.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Optional. Email addresses associated with the agent. Required if phone number and website are
   * not provided.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<EmailEntry> emails;

  /**
   * Required. Publicly available URL of the hero image for the agent. Maximum 200 KB. Not
   * modifiable after agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String heroUri;

  /**
   * Required. Hosting region for an agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hostingRegion;

  /**
   * Output only. Launch details for the agent. Only populated for carriers, and only with the
   * launch details related to the carrier making the call.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, RcsBusinessMessagingRegionLaunch> launchDetails;

  /**
   * Required. Publicly available URL of the logo for the agent. Maximum 50 KB. Not modifiable after
   * agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoUri;

  /**
   * Output only. Partner associated with the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private PartnerEntry partner;

  /**
   * Optional. Phone numbers associated with the agent. Required if email and website are not
   * provided.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PhoneEntry> phoneNumbers;

  /**
   * Required. Privacy policy associated with the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private WebEntry privacy;

  /**
   * Required. Terms and conditions associated with the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private WebEntry termsConditions;

  /**
   * Optional. Websites associated with the agent. Maximum 3. Required if phone number and email are
   * not provided.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<WebEntry> websites;

  /**
   * Optional. Use case of bot.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentUseCase() {
    return agentUseCase;
  }

  /**
   * Optional. Use case of bot.
   * @param agentUseCase agentUseCase or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setAgentUseCase(java.lang.String agentUseCase) {
    this.agentUseCase = agentUseCase;
    return this;
  }

  /**
   * Required. Billing configuration for the agent.
   * @return value or {@code null} for none
   */
  public RcsBusinessMessagingAgentBillingConfig getBillingConfig() {
    return billingConfig;
  }

  /**
   * Required. Billing configuration for the agent.
   * @param billingConfig billingConfig or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setBillingConfig(RcsBusinessMessagingAgentBillingConfig billingConfig) {
    this.billingConfig = billingConfig;
    return this;
  }

  /**
   * Required. Theme color of the agent that is visible to users in hex format. For example,
   * #FF6347.
   * @return value or {@code null} for none
   */
  public java.lang.String getColor() {
    return color;
  }

  /**
   * Required. Theme color of the agent that is visible to users in hex format. For example,
   * #FF6347.
   * @param color color or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setColor(java.lang.String color) {
    this.color = color;
    return this;
  }

  /**
   * Required. Description of the agent that is visible to users. Maximum 100 characters. See [Edit
   * agent information](https://developers.google.com/business-communications/rcs-business-
   * messaging/guides/build/agents/edit-agent-information?hl=en#edit_your_agents_information) for
   * detailed requirements.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Required. Description of the agent that is visible to users. Maximum 100 characters. See [Edit
   * agent information](https://developers.google.com/business-communications/rcs-business-
   * messaging/guides/build/agents/edit-agent-information?hl=en#edit_your_agents_information) for
   * detailed requirements.
   * @param description description or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Optional. Email addresses associated with the agent. Required if phone number and website are
   * not provided.
   * @return value or {@code null} for none
   */
  public java.util.List<EmailEntry> getEmails() {
    return emails;
  }

  /**
   * Optional. Email addresses associated with the agent. Required if phone number and website are
   * not provided.
   * @param emails emails or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setEmails(java.util.List<EmailEntry> emails) {
    this.emails = emails;
    return this;
  }

  /**
   * Required. Publicly available URL of the hero image for the agent. Maximum 200 KB. Not
   * modifiable after agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getHeroUri() {
    return heroUri;
  }

  /**
   * Required. Publicly available URL of the hero image for the agent. Maximum 200 KB. Not
   * modifiable after agent verification.
   * @param heroUri heroUri or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setHeroUri(java.lang.String heroUri) {
    this.heroUri = heroUri;
    return this;
  }

  /**
   * Required. Hosting region for an agent.
   * @return value or {@code null} for none
   */
  public java.lang.String getHostingRegion() {
    return hostingRegion;
  }

  /**
   * Required. Hosting region for an agent.
   * @param hostingRegion hostingRegion or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setHostingRegion(java.lang.String hostingRegion) {
    this.hostingRegion = hostingRegion;
    return this;
  }

  /**
   * Output only. Launch details for the agent. Only populated for carriers, and only with the
   * launch details related to the carrier making the call.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, RcsBusinessMessagingRegionLaunch> getLaunchDetails() {
    return launchDetails;
  }

  /**
   * Output only. Launch details for the agent. Only populated for carriers, and only with the
   * launch details related to the carrier making the call.
   * @param launchDetails launchDetails or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setLaunchDetails(java.util.Map<String, RcsBusinessMessagingRegionLaunch> launchDetails) {
    this.launchDetails = launchDetails;
    return this;
  }

  /**
   * Required. Publicly available URL of the logo for the agent. Maximum 50 KB. Not modifiable after
   * agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoUri() {
    return logoUri;
  }

  /**
   * Required. Publicly available URL of the logo for the agent. Maximum 50 KB. Not modifiable after
   * agent verification.
   * @param logoUri logoUri or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setLogoUri(java.lang.String logoUri) {
    this.logoUri = logoUri;
    return this;
  }

  /**
   * Output only. Partner associated with the agent.
   * @return value or {@code null} for none
   */
  public PartnerEntry getPartner() {
    return partner;
  }

  /**
   * Output only. Partner associated with the agent.
   * @param partner partner or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setPartner(PartnerEntry partner) {
    this.partner = partner;
    return this;
  }

  /**
   * Optional. Phone numbers associated with the agent. Required if email and website are not
   * provided.
   * @return value or {@code null} for none
   */
  public java.util.List<PhoneEntry> getPhoneNumbers() {
    return phoneNumbers;
  }

  /**
   * Optional. Phone numbers associated with the agent. Required if email and website are not
   * provided.
   * @param phoneNumbers phoneNumbers or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setPhoneNumbers(java.util.List<PhoneEntry> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  /**
   * Required. Privacy policy associated with the agent.
   * @return value or {@code null} for none
   */
  public WebEntry getPrivacy() {
    return privacy;
  }

  /**
   * Required. Privacy policy associated with the agent.
   * @param privacy privacy or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setPrivacy(WebEntry privacy) {
    this.privacy = privacy;
    return this;
  }

  /**
   * Required. Terms and conditions associated with the agent.
   * @return value or {@code null} for none
   */
  public WebEntry getTermsConditions() {
    return termsConditions;
  }

  /**
   * Required. Terms and conditions associated with the agent.
   * @param termsConditions termsConditions or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setTermsConditions(WebEntry termsConditions) {
    this.termsConditions = termsConditions;
    return this;
  }

  /**
   * Optional. Websites associated with the agent. Maximum 3. Required if phone number and email are
   * not provided.
   * @return value or {@code null} for none
   */
  public java.util.List<WebEntry> getWebsites() {
    return websites;
  }

  /**
   * Optional. Websites associated with the agent. Maximum 3. Required if phone number and email are
   * not provided.
   * @param websites websites or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingAgent setWebsites(java.util.List<WebEntry> websites) {
    this.websites = websites;
    return this;
  }

  @Override
  public RcsBusinessMessagingAgent set(String fieldName, Object value) {
    return (RcsBusinessMessagingAgent) super.set(fieldName, value);
  }

  @Override
  public RcsBusinessMessagingAgent clone() {
    return (RcsBusinessMessagingAgent) super.clone();
  }

}
