/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Details about RCS for Business agent launch for each region.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RcsBusinessMessagingRegionLaunch extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Specifies the party designation of the agent launch.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentLaunchPartyDesignation;

  /**
   * Comment from the carrier.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String comment;

  /**
   * The launch state for a region.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String launchState;

  /**
   * Last updated time.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String updateTime;

  /**
   * Optional. Specifies the party designation of the agent launch.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentLaunchPartyDesignation() {
    return agentLaunchPartyDesignation;
  }

  /**
   * Optional. Specifies the party designation of the agent launch.
   * @param agentLaunchPartyDesignation agentLaunchPartyDesignation or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingRegionLaunch setAgentLaunchPartyDesignation(java.lang.String agentLaunchPartyDesignation) {
    this.agentLaunchPartyDesignation = agentLaunchPartyDesignation;
    return this;
  }

  /**
   * Comment from the carrier.
   * @return value or {@code null} for none
   */
  public java.lang.String getComment() {
    return comment;
  }

  /**
   * Comment from the carrier.
   * @param comment comment or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingRegionLaunch setComment(java.lang.String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * The launch state for a region.
   * @return value or {@code null} for none
   */
  public java.lang.String getLaunchState() {
    return launchState;
  }

  /**
   * The launch state for a region.
   * @param launchState launchState or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingRegionLaunch setLaunchState(java.lang.String launchState) {
    this.launchState = launchState;
    return this;
  }

  /**
   * Last updated time.
   * @return value or {@code null} for none
   */
  public String getUpdateTime() {
    return updateTime;
  }

  /**
   * Last updated time.
   * @param updateTime updateTime or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RcsBusinessMessagingRegionLaunch setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  @Override
  public RcsBusinessMessagingRegionLaunch set(String fieldName, Object value) {
    return (RcsBusinessMessagingRegionLaunch) super.set(fieldName, value);
  }

  @Override
  public RcsBusinessMessagingRegionLaunch clone() {
    return (RcsBusinessMessagingRegionLaunch) super.clone();
  }

}
