/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Request to begin business information verification for an agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RequestAgentVerificationRequest extends com.google.api.client.json.GenericJson {

  /**
   * Required. Verification contact details for the agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AgentVerificationContact agentVerificationContact;

  /**
   * Required. Verification contact details for the agent.
   * @return value or {@code null} for none
   */
  public AgentVerificationContact getAgentVerificationContact() {
    return agentVerificationContact;
  }

  /**
   * Required. Verification contact details for the agent.
   * @param agentVerificationContact agentVerificationContact or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public RequestAgentVerificationRequest setAgentVerificationContact(AgentVerificationContact agentVerificationContact) {
    this.agentVerificationContact = agentVerificationContact;
    return this;
  }

  @Override
  public RequestAgentVerificationRequest set(String fieldName, Object value) {
    return (RequestAgentVerificationRequest) super.set(fieldName, value);
  }

  @Override
  public RequestAgentVerificationRequest clone() {
    return (RequestAgentVerificationRequest) super.clone();
  }

}
