/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * RCS for Business subscriber profile information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SubscriberProfile extends com.google.api.client.json.GenericJson {

  /**
   * Optional. If true, no messages are sent to this number unless they are from critical agents. If
   * false, no messages are sent to this number from agents on blockedAgentIds list. If not
   * specified, will default to false.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean blockAll;

  /**
   * Optional. Cannot send messages even if block_all is false.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> blockedAgentIds;

  /**
   * Required. Output only. Identifier. The phone number of the subscriber profile in E.164 format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * For carriers that disallow test devices by default, this means that the phone number can
   * receive test messages even for such a carrier. For carriers that allow test devices, this does
   * nothing.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean testingAllowed;

  /**
   * Optional. If true, no messages are sent to this number unless they are from critical agents. If
   * false, no messages are sent to this number from agents on blockedAgentIds list. If not
   * specified, will default to false.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBlockAll() {
    return blockAll;
  }

  /**
   * Optional. If true, no messages are sent to this number unless they are from critical agents. If
   * false, no messages are sent to this number from agents on blockedAgentIds list. If not
   * specified, will default to false.
   * @param blockAll blockAll or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SubscriberProfile setBlockAll(java.lang.Boolean blockAll) {
    this.blockAll = blockAll;
    return this;
  }

  /**
   * Optional. Cannot send messages even if block_all is false.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getBlockedAgentIds() {
    return blockedAgentIds;
  }

  /**
   * Optional. Cannot send messages even if block_all is false.
   * @param blockedAgentIds blockedAgentIds or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SubscriberProfile setBlockedAgentIds(java.util.List<java.lang.String> blockedAgentIds) {
    this.blockedAgentIds = blockedAgentIds;
    return this;
  }

  /**
   * Required. Output only. Identifier. The phone number of the subscriber profile in E.164 format.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Required. Output only. Identifier. The phone number of the subscriber profile in E.164 format.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SubscriberProfile setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * For carriers that disallow test devices by default, this means that the phone number can
   * receive test messages even for such a carrier. For carriers that allow test devices, this does
   * nothing.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTestingAllowed() {
    return testingAllowed;
  }

  /**
   * For carriers that disallow test devices by default, this means that the phone number can
   * receive test messages even for such a carrier. For carriers that allow test devices, this does
   * nothing.
   * @param testingAllowed testingAllowed or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SubscriberProfile setTestingAllowed(java.lang.Boolean testingAllowed) {
    this.testingAllowed = testingAllowed;
    return this;
  }

  @Override
  public SubscriberProfile set(String fieldName, Object value) {
    return (SubscriberProfile) super.set(fieldName, value);
  }

  @Override
  public SubscriberProfile clone() {
    return (SubscriberProfile) super.clone();
  }

}
