/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * The detailed content of each survey question.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveyQuestion extends com.google.api.client.json.GenericJson {

  /**
   * Required. The unique identifier of the question.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Required. Question content. Limited to 200 characters for custom questions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String questionContent;

  /**
   * Output only. Type of the question.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String questionType;

  /**
   * Required. List of responses displayed with the question. Maximum 12.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<SurveyResponse> responseOptions;

  /**
   * Required. The unique identifier of the question.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Required. The unique identifier of the question.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyQuestion setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Required. Question content. Limited to 200 characters for custom questions.
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestionContent() {
    return questionContent;
  }

  /**
   * Required. Question content. Limited to 200 characters for custom questions.
   * @param questionContent questionContent or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyQuestion setQuestionContent(java.lang.String questionContent) {
    this.questionContent = questionContent;
    return this;
  }

  /**
   * Output only. Type of the question.
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestionType() {
    return questionType;
  }

  /**
   * Output only. Type of the question.
   * @param questionType questionType or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyQuestion setQuestionType(java.lang.String questionType) {
    this.questionType = questionType;
    return this;
  }

  /**
   * Required. List of responses displayed with the question. Maximum 12.
   * @return value or {@code null} for none
   */
  public java.util.List<SurveyResponse> getResponseOptions() {
    return responseOptions;
  }

  /**
   * Required. List of responses displayed with the question. Maximum 12.
   * @param responseOptions responseOptions or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyQuestion setResponseOptions(java.util.List<SurveyResponse> responseOptions) {
    this.responseOptions = responseOptions;
    return this;
  }

  @Override
  public SurveyQuestion set(String fieldName, Object value) {
    return (SurveyQuestion) super.set(fieldName, value);
  }

  @Override
  public SurveyQuestion clone() {
    return (SurveyQuestion) super.clone();
  }

}
