/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A tester for the agent. The agent can interact with verified testers even if the agent has not
 * yet launched.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Tester extends com.google.api.client.json.GenericJson {

  /**
   * Agent ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentId;

  /**
   * Output only. The status of the invitation. Read-only. Returned by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inviteStatus;

  /**
   * Output only. ReadOnly. The unique identifier of the tester. This field should resolve to
   * "testers/{E.164}" where {E.164} is the tester's phone number in E.164 format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Required. The phone number of the tester in E.164 format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phoneNumber;

  /**
   * Agent ID.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentId() {
    return agentId;
  }

  /**
   * Agent ID.
   * @param agentId agentId or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Tester setAgentId(java.lang.String agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * Output only. The status of the invitation. Read-only. Returned by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getInviteStatus() {
    return inviteStatus;
  }

  /**
   * Output only. The status of the invitation. Read-only. Returned by the platform.
   * @param inviteStatus inviteStatus or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Tester setInviteStatus(java.lang.String inviteStatus) {
    this.inviteStatus = inviteStatus;
    return this;
  }

  /**
   * Output only. ReadOnly. The unique identifier of the tester. This field should resolve to
   * "testers/{E.164}" where {E.164} is the tester's phone number in E.164 format.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Output only. ReadOnly. The unique identifier of the tester. This field should resolve to
   * "testers/{E.164}" where {E.164} is the tester's phone number in E.164 format.
   * @param name name or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Tester setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Required. The phone number of the tester in E.164 format.
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Required. The phone number of the tester in E.164 format.
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public Tester setPhoneNumber(java.lang.String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  @Override
  public Tester set(String fieldName, Object value) {
    return (Tester) super.set(fieldName, value);
  }

  @Override
  public Tester clone() {
    return (Tester) super.clone();
  }

}
