/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A web-based resource associated with the agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class WebEntry extends com.google.api.client.json.GenericJson {

  /**
   * Required. Label for the URI.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * Required. A publicly accessible URI associated with the agent. Must use the HTTP or HTTPS
   * protocol.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String uri;

  /**
   * Required. Label for the URI.
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * Required. Label for the URI.
   * @param label label or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public WebEntry setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  /**
   * Required. A publicly accessible URI associated with the agent. Must use the HTTP or HTTPS
   * protocol.
   * @return value or {@code null} for none
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * Required. A publicly accessible URI associated with the agent. Must use the HTTP or HTTPS
   * protocol.
   * @param uri uri or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public WebEntry setUri(java.lang.String uri) {
    this.uri = uri;
    return this;
  }

  @Override
  public WebEntry set(String fieldName, Object value) {
    return (WebEntry) super.set(fieldName, value);
  }

  @Override
  public WebEntry clone() {
    return (WebEntry) super.clone();
  }

}
