/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.rcsbusinessmessaging.v1.model;

/**
 * Compose and send a message to a destination predefined by chatbot. To check whether a user's
 * device supports this action, run a capability check first. See the documentation for details:
 * https://developers.google.com/business-communications/rcs-business-
 * messaging/guides/build/capabilities.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ComposeAction extends com.google.api.client.json.GenericJson {

  /**
   * Initiate the recording and sending of an audio or video message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ComposeRecordingMessage composeRecordingMessage;

  /**
   * Compose and send a text message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ComposeTextMessage composeTextMessage;

  /**
   * Initiate the recording and sending of an audio or video message.
   * @return value or {@code null} for none
   */
  public ComposeRecordingMessage getComposeRecordingMessage() {
    return composeRecordingMessage;
  }

  /**
   * Initiate the recording and sending of an audio or video message.
   * @param composeRecordingMessage composeRecordingMessage or {@code null} for none
   */
  public ComposeAction setComposeRecordingMessage(ComposeRecordingMessage composeRecordingMessage) {
    this.composeRecordingMessage = composeRecordingMessage;
    return this;
  }

  /**
   * Compose and send a text message.
   * @return value or {@code null} for none
   */
  public ComposeTextMessage getComposeTextMessage() {
    return composeTextMessage;
  }

  /**
   * Compose and send a text message.
   * @param composeTextMessage composeTextMessage or {@code null} for none
   */
  public ComposeAction setComposeTextMessage(ComposeTextMessage composeTextMessage) {
    this.composeTextMessage = composeTextMessage;
    return this;
  }

  @Override
  public ComposeAction set(String fieldName, Object value) {
    return (ComposeAction) super.set(fieldName, value);
  }

  @Override
  public ComposeAction clone() {
    return (ComposeAction) super.clone();
  }

}
